# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://registry.k8s.io/kube-apiserver:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/kube-apiserver:v1.31.3
        skopeo copy --all docker://registry.k8s.io/kube-controller-manager:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/kube-controller-manager:v1.31.3
        skopeo copy --all docker://registry.k8s.io/kube-scheduler:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/kube-scheduler:v1.31.3
        skopeo copy --all docker://registry.k8s.io/kube-proxy:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/kube-proxy:v1.31.3
        skopeo copy --all docker://registry.k8s.io/coredns/coredns:v1.11.3 docker://registry.cn-beijing.aliyuncs.com/coredns:v1.11.3
        skopeo copy --all docker://registry.k8s.io/pause:3.10 docker://registry.cn-beijing.aliyuncs.com/pause:3.10
        skopeo copy --all docker://registry.k8s.io/etcd:3.5.15-0 docker://registry.cn-beijing.aliyuncs.com/etcd:3.5.15-0
