# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-beijing.aliyuncs.com
        region-id: cn-beijing  # 3
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://k8s.gcr.io/kube-apiserver:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/qiyitest/kube-apiserver:v1.31.3
        skopeo copy --all docker://k8s.gcr.io/kube-controller-manager:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/qiyitest/kube-controller-manager:v1.31.3
        skopeo copy --all docker://k8s.gcr.io/kube-scheduler:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/qiyitest/kube-scheduler:v1.31.3
        skopeo copy --all docker://k8s.gcr.io/kube-proxy:v1.31.3 docker://registry.cn-beijing.aliyuncs.com/qiyitest/kube-proxy:v1.31.3
        skopeo copy --all docker://k8s.gcr.io/coredns/coredns:v1.11.3 docker://registry.cn-beijing.aliyuncs.com/qiyitest/coredns:v1.11.3
        skopeo copy --all docker://k8s.gcr.io/pause:3.10 docker://registry.cn-beijing.aliyuncs.com/qiyitest/pause:3.10
        skopeo copy --all docker://k8s.gcr.io/etcd:3.5.15-0 docker://registry.cn-beijing.aliyuncs.com/qiyitest/etcd:3.5.15-0
